services:

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://user:password@pg:5432/shortener
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    command: "-c listen_addresses='*'"
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy
  
  redis:
    image: redis:8
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
  
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    depends_on:
      pg:
        condition: service_healthy     

  tests:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://user:password@pg:5432/shortener
    depends_on:
      pg:
        condition: service_healthy
    command: python -m pytest -v --maxfail=1
        
volumes:
  postgres_data:
  redis_data: