"""Add Detail Click log

Revision ID: ae303db295bd
Revises: a2be500c9dfe
Create Date: 2026-07-31 15:56:41.815246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae303db295bd'
down_revision: Union[str, Sequence[str], None] = 'a2be500c9dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], name=op.f('fk_click_log_link_id_link')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_click_log'))
    )
    op.create_index(op.f('ix_click_log_created_at'), 'click_log', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_log_created_at'), table_name='click_log')
    op.drop_table('click_log')
    # ### end Alembic commands ###
