"""Update table

Revision ID: b121079187d7
Revises: 9f215eb40bbc
Create Date: 2026-07-16 15:33:54.951304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b121079187d7'
down_revision: Union[str, Sequence[str], None] = '9f215eb40bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('link', 'created_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('link', 'created_at')
    # ### end Alembic commands ###
