"""Delete short_url column

Revision ID: bdb5d6accd1b
Revises: 1500fce41ccd
Create Date: 2026-08-08 12:11:37.631762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb5d6accd1b'
down_revision: Union[str, Sequence[str], None] = '1500fce41ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'short_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
