"""add is_admin to user

Revision ID: a2be500c9dfe
Revises: 7b934a2e1935
Create Date: 2026-07-30 15:09:48.820543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2be500c9dfe'
down_revision: Union[str, Sequence[str], None] = '7b934a2e1935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=True))
    op.execute("UPDATE \"user\" SET is_admin = FALSE WHERE is_admin IS NULL")
    op.alter_column("user", "is_admin", existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
